### PR TITLE
🦺 Couple Minor Changes (Enhancement) 

### PR DESCRIPTION
**Pull request by HypnoticSiege**
- Added a view files page (Website only)
- Added a navbar kinda
- One central configuration
- Component based header and footer for making new pages
- That's really it except maybe some smaller changes I forgot to leave out!

### CODE REVIEW

**Comment by braxtongpoll** [comment]
You are aware the website and script are two separate items?

**Comment by HypnoticSiege** [comment]
Oopsies, my bad. You can revert those changes then and only Push the view files all that jazz. 😅 
Thought they were "together" in a way

**Review by FAXES — CHANGES_REQUESTED** [review]
Some files need changes to be compatible with others like the config in the website index for example.

Other files like package-lock.json and git files are ignored as they're not needed in these releases.

**Review by FAXES — COMMENTED** [review]
Sorry for all the changes had a moment 😆 

@braxtongpoll will also review.

**Review by FAXES — APPROVED** [review]

**Review by braxtongpoll — APPROVED** [review]

**Pull request merged**
