### PR TITLE
Displays Local Date instead of numbers for the same value

### PR DESCRIPTION
**Pull request by SkylarPlayz348**
just fixed the backup thing where it says "filename-numbersfordate.js" where now it will say "filename-MM or DD/MM or DD/ YYYY.js"

### CODE REVIEW

**Review by FAXES — CHANGES_REQUESTED** [review]
Great PR but some updates are needed to be compatible on all OS'.

[line 53](https://github.com/FAXES/easycompile/blob/d712a5471b532a264bb58da720632e6f4752f34e/script/index.js#L53) will cause issues as `.toLocaleDateString()` will return with `/` characters which might cause issues on Windows especially. Maybe updating this function to use [`toDateString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toDateString)  will be better. Along with this `date` isn't defined inside the function which currently causes the date to be the same throughout all file names.

```js
new Date(Date.now()).toDateString().replaceAll(" ", "-")
```
*The `replaceAll()` is optional. However, will remove spaces in our date string to make it formatted like `Thu-Mar-10-2022`.*

Would be a better option to update too.

Otherwise, [line 30](https://github.com/FAXES/easycompile/blob/d712a5471b532a264bb58da720632e6f4752f34e/script/index.js#L30) should reflect the same date functionality.

**Comment by SkylarPlayz348** [comment]
Fixed

**Review by FAXES — CHANGES_REQUESTED** [review]
Perfect,

The `date` variable just needs to be moved into both functions as it being at the very top will mean it executes and is declared there. Meaning the date is set when the script is started and not when a file is comliped.

**Review by FAXES — APPROVED** [review]

**Review by braxtongpoll — CHANGES_REQUESTED** [review]
I'd recommend still providing the millisecond time stamp in the file name to avoid conflict of a possible overlap of the same file name on the same day. Thus possibly making the file name 
```js
fs.writeFileSync(path.join(__dirname, ".backups/", `${file.split(".")[0]}-${date}-${Date.now()}.js`), data):
```

**Comment by braxtongpoll** [comment]
Ignore above adding changes myself.

**Review by braxtongpoll — APPROVED** [review]

**Pull request merged**
